# experiment params
sample_size: 14 # number of NNs to train on each category
verbose: False # whether to print intermediate output

# files
filepaths:
  datasets: outputs/cnn0/datasets
  learning_results: outputs/cnn0/learning_results.npz
  plot: outputs/cnn0/plot.png
  sample_loss: outputs/cnn0/sample_loss.png
  sample_accuracy: outputs/cnn0/sample_accuracy.png
  analysis: outputs/cnn0/analysis.csv

# network hyperparams
learner: CNN0
num_epochs: 100
batch_size: 1
learning_rate: 1e-2
