# experiment params
sample_size: 2 # number of NNs to train on each category

# files
filepaths:
  datasets: outputs/dev/datasets
  learning_results: outputs/dev/learning_results.npz

# network hyperparams
num_epochs: 4
batch_size: 8
learning_rate: 1e-3

# network architecture
