# experiment params
sample_size: 5 # number of NNs to train on each category

# files
filepaths:
  datasets: outputs/dev/datasets
  learning_results: outputs/dev/learning_results.npz
  plot: outputs/dev/plot.png

# network hyperparams
num_epochs: 100
batch_size: 8
learning_rate: 1e-4

# network architecture
