# experiment params
sample_size: 14 # number of NNs to train on each category
verbose: False # whether to print intermediate output

# files
filepaths:
  datasets: outputs/dev/datasets
  learning_results: outputs/dev/learning_results.npz
  plot: outputs/dev/plot.png
  sample_loss: outputs/dev/sample_loss.png

# network hyperparams
num_epochs: 100
batch_size: 1
learning_rate: 1e-1

# network architecture
