# experiment params
sample_size: 14 # number of NNs to train on each category
verbose: False # whether to print intermediate output

# files
filepaths:
  datasets: outputs/mlp1/datasets
  learning_results: outputs/mlp1/learning_results.npz
  plot: outputs/mlp1/plot.png
  sample_loss: outputs/mlp1/sample_loss.png
  sample_accuracy: outputs/mlp1/sample_accuracy.png
  analysis: outputs/mlp1/analysis.csv    

# network hyperparams
learner: MLP1
num_epochs: 100
batch_size: 1
learning_rate: 1e-2
